add:
  float:
    datas:
      - [ 0.1, 0.1, 0.2 ]
      - [ 0.1, 0.2, 0.3 ]
    ids: [ float1, float2 ]
  int:
    datas:
      - [ 1, 1, 2 ]
      - [ 100, 100, 200 ]
      - [ 0, 1, 1 ]
    ids: [ int, bigint, zero ]
